---
# Service to expose frontend
apiVersion: v1
kind: Service
metadata:
  name: todo
  labels:
    app: todo
    tier: frontend
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: todo
    tier: frontend
---
# Application to deploy
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: todo
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: todo
        tier: frontend
    spec:
      containers:
      - name: todo
        image: registry.eu-gb.bluemix.net/mace/todo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
          - name: CONVERSATION_SERVICE_CAR
            valueFrom:
              secretKeyRef:
                name: binding-conversation-service-car
                key: binding
