---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mytodos-autoscaler
spec:
  scaleTargetRef:
    kind: Deployment
    name: mytodos
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70